{
 "title": "Solar Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Wärme-Ertrag pro Tag [Wh]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date1 AS \"time\",\n  heat_today\nFROM heizung_pro_tag\nWHERE\n  $__timeFilter(date1)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperaturen Primärkreislauf",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date1 AS \"time\",\n  s1\nFROM heizung\nWHERE\n  $__timeFilter(date1) AND\n  s1 > 0\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  date1 AS \"time\",\n  s2\nFROM heizung\nWHERE\n  $__timeFilter(date1) AND\n  s2 > 0\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  date1 AS \"time\",\n  s3\nFROM heizung\nWHERE\n  $__timeFilter(date1) AND\n  s3 > 0\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  date1 AS \"time\",\n  s9\nFROM heizung\nWHERE\n  $__timeFilter(date1) AND\n  s9 > 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Solar-Speicher-Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date1 AS \"time\",\n  s2\nFROM heizung\nWHERE\n  $__timeFilter(date1) AND\n  s2 > 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pumpenaktivität im Primärkreislauf",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date1,$__interval),\n  avg(r1) AS \"Primärpumpe (R1)\"\nFROM heizung\nWHERE\n  $__timeFilter(date1)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date1,$__interval),\n  avg(r3) AS \"Sekundärpumpe (R3)\"\nFROM heizung\nWHERE\n  $__timeFilter(date1)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Heat transmitted",
   "type": "timeseries",
   "description": "increase in \"heat\"",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date1,$__interval),\n  (CASE WHEN max(heat) >= lag(max(heat)) OVER (ORDER BY $__timeGroup(date1,$__interval)) THEN max(heat) - lag(max(heat)) OVER (ORDER BY $__timeGroup(date1,$__interval)) WHEN lag(max(heat)) OVER (ORDER BY $__timeGroup(date1,$__interval)) IS NULL THEN NULL ELSE max(heat) END) AS \"heat\"\nFROM heizung\nWHERE\n  $__timeFilter(date1)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Wärme-Ertrag pro Woche",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date1,$__interval),\n  sum(heat_today) AS \"heat_today\"\nFROM heizung_pro_tag\nWHERE\n  $__timeFilter(date1)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}