version: "3.7"

services:
  grafana:
    image: grafana/grafana:6.7.1-ubuntu
    networks: 
      - grafnet
    ports:
      - 3000:3000
    volumes:
      - grafana-storage
      - ./datasources.yml:/etc/grafana/provisioning/datasources/all.yml
      - ./dashboards.yml:/etc/grafana/provisioning/dashboards/all.yml
      - ./dashboard.json:/var/lib/grafana/dashboards/solar-dashboard.json
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      
  postgres:
    image: postgres:9
    container_name: postgres
    networks: 
      - grafnet
    environment:
      - POSTGRES_PASSWORD=${PG_ADMIN_PASSWORD}
    volumes:
      - ${SOLAR_HEAT_DIR}:/tmp/SC514:ro

networks:
  grafnet: