services:
  grafana:
    image: grafana/grafana:6.7.1-ubuntu
    networks:
      - grafnet
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./datasources.yml:/etc/grafana/provisioning/datasources/all.yml:ro
      - ./dashboards.yml:/etc/grafana/provisioning/dashboards/all.yml:ro
      - ./dashboard.json:/var/lib/grafana/dashboards/solar-dashboard.json:ro
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:9
    container_name: postgres
    networks:
      - grafnet
    environment:
      - POSTGRES_PASSWORD=${PG_ADMIN_PASSWORD}
    volumes:
      - ${SOLAR_HEAT_DIR}:/tmp/SC514:ro
    restart: unless-stopped

networks:
  grafnet:

volumes:
  # created by init-docker.sh
  grafana-storage:
    external: true
