version: "3.7"

services:
  grafana:
    image: grafana/grafana:6.7.1-ubuntu
    networks: 
      - grafnet
      - frontnet
    ports:
      - 3000:3000
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/all.yml
      - ./dashboards.yml:/etc/grafana/provisioning/dashboards/all.yml
      - ./dashboard.json:/var/lib/grafana/dashboards/solar-dashboard.json
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      
  postgres:
    image: postgres:9
    container_name: postgres
    networks: 
      - grafnet
    environment:
      - POSTGRES_PASSWORD=${PG_ADMIN_PASSWORD}
    volumes:
      - ${SOLAR_HEAT_DIR}:/tmp/SC514:ro
      - ./data/postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:1.16-alpine
    networks:
      - frontnet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  grafnet:
  frontnet: